services:
  - type: web
    name: cd-billing-baileys
    runtime: node
    plan: free
    region: singapore
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node baileys-server.mjs
    envVars:
      - key: PORT
        value: 10000
